/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 ../public/Maleta.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Maleta.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suitcase.geometry} material={materials['Material.001']}>
        <mesh geometry={nodes.Handle.geometry} material={materials['Material.001']} position={[0, -0.001, 0]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Maleta.glb')
